package com.fdmultimedia.api.publishing.tiktok;

import static com.fdmultimedia.api.publishing.tiktok.TikTokModels.*;
import java.io.IOException; import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.*; import java.util.*;
import org.springframework.stereotype.Component; import tools.jackson.databind.*;

@Component
public class TikTokApiClient {
 private static final int MAX_JSON=1024*1024;
 private final TikTokProperties p; private final ObjectMapper json; private final HttpClient http;
 public TikTokApiClient(TikTokProperties p,ObjectMapper json){this.p=p;this.json=json;http=HttpClient.newBuilder().connectTimeout(p.getConnectTimeout()).followRedirects(HttpClient.Redirect.NEVER).build();}
 public String authorizationUrl(String state){return p.getAuthorizeUrl()+"?client_key="+enc(p.getClientKey())+"&response_type=code&scope="+enc("video.publish")+"&redirect_uri="+enc(p.getOauthRedirectUri())+"&state="+enc(state);}
 public Token exchange(String code){return token(form(Map.of("client_key",p.getClientKey(),"client_secret",p.getClientSecret(),"code",code,"grant_type","authorization_code","redirect_uri",p.getOauthRedirectUri())));}
 public Token refresh(String refresh){return token(form(Map.of("client_key",p.getClientKey(),"client_secret",p.getClientSecret(),"refresh_token",refresh,"grant_type","refresh_token")));}
 public CreatorInfo creatorInfo(String access){JsonNode d=post("/v2/post/publish/creator_info/query/",access,"{}").path("data"); List<String> opts=new ArrayList<>();d.path("privacy_level_options").forEach(n->opts.add(n.asText()));int max=d.path("max_video_post_duration_sec").asInt(0);if(opts.isEmpty()||max<=0)throw new TikTokApiException("PROVIDER_INVALID_RESPONSE","TikTok creator information was incomplete",false);return new CreatorInfo(d.path("creator_username").asText(""),d.path("creator_nickname").asText(""),List.copyOf(opts),d.path("comment_disabled").asBoolean(),d.path("duet_disabled").asBoolean(),d.path("stitch_disabled").asBoolean(),max);}
 public Init initialize(String access,TikTokPublicationSettings s,String title,long size){long[] plan=chunkPlan(size);long chunk=plan[0],count=plan[1];String body="{\"post_info\":{\"title\":"+q(title)+",\"privacy_level\":"+q(s.getPrivacyLevel())+",\"disable_comment\":"+s.isDisableComment()+",\"disable_duet\":"+s.isDisableDuet()+",\"disable_stitch\":"+s.isDisableStitch()+",\"is_aigc\":"+s.isAigc()+",\"brand_organic_toggle\":"+s.isBrandOrganic()+"},\"source_info\":{\"source\":\"FILE_UPLOAD\",\"video_size\":"+size+",\"chunk_size\":"+chunk+",\"total_chunk_count\":"+count+"}}";JsonNode d=post("/v2/post/publish/video/init/",access,body).path("data");String id=d.path("publish_id").asText(null),url=d.path("upload_url").asText(null);validateUploadUrl(url);if(id==null)throw new TikTokApiException("PROVIDER_OUTCOME_UNKNOWN","TikTok initialization outcome is unknown",false,true);return new Init(id,url);}
 public void upload(String uploadUrl,Path file,String type) throws IOException,InterruptedException {validateUploadUrl(uploadUrl);sendChunks(URI.create(uploadUrl),file,type);}
 /** Single source of truth for chunk boundaries: {chunkSize, totalChunkCount}, shared by initialize() (which declares the plan to TikTok) and sendChunks() (which executes it), so the two can never diverge. Follows TikTok's documented FILE_UPLOAD rule: total_chunk_count = floor(video_size / chunk_size), chunks are 5MB-64MB, and the last chunk absorbs the remainder (up to 128MB). Package-private so it can be unit tested directly. */
 long[] chunkPlan(long size){if(size<=0)throw new TikTokApiException("MEDIA_NOT_ELIGIBLE","TikTok video size must be positive",false);long minChunk=5L*1024*1024,maxChunk=64L*1024*1024;if(size<minChunk)return new long[]{size,1};long chunk=Math.max(minChunk,Math.min(maxChunk,p.getChunkBytes()));if(size<=chunk)return new long[]{size,1};return new long[]{chunk,size/chunk};}
 /** Executes the chunkPlan() for {@code file} against {@code uri} with no host validation of its own — callers (upload()) must validate the destination first. Package-private so tests can exercise real chunk/Content-Range behavior against a local mock server without needing a host that passes the production SSRF allowlist. */
 void sendChunks(URI uri,Path file,String type) throws IOException,InterruptedException {long total=Files.size(file);long[] plan=chunkPlan(total);long chunkSize=plan[0],count=plan[1];long offset=0;try(var in=Files.newInputStream(file)){for(long i=0;i<count;i++){boolean last=i==count-1;int requested=(int)(last?(total-offset):chunkSize);byte[] part=in.readNBytes(requested);long end=offset+part.length-1;HttpRequest req=HttpRequest.newBuilder(uri).timeout(p.getUploadTimeout()).header("Content-Type",type).header("Content-Range","bytes "+offset+"-"+end+"/"+total).PUT(HttpRequest.BodyPublishers.ofByteArray(part)).build();HttpResponse<String> res=http.send(req,HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));if((last&&res.statusCode()!=201)||(!last&&res.statusCode()!=206))throw map(res.statusCode(),null,"TikTok upload failed",false);offset=end+1;}}}
 public Status status(String access,String publishId){JsonNode d=post("/v2/post/publish/status/fetch/",access,"{\"publish_id\":"+q(publishId)+"}").path("data");return new Status(d.path("status").asText("PROCESSING_UPLOAD"),d.path("publicaly_available_post_id").isArray()&&d.path("publicaly_available_post_id").size()>0?d.path("publicaly_available_post_id").get(0).asText(null):null,d.path("fail_reason").asText(null));}
 private Token token(String body){JsonNode n=send(HttpRequest.newBuilder(URI.create(p.getApiBaseUrl()+"/v2/oauth/token/")).timeout(p.getReadTimeout()).header("Content-Type","application/x-www-form-urlencoded").POST(HttpRequest.BodyPublishers.ofString(body)).build(),true);String access=n.path("access_token").asText(null),refresh=n.path("refresh_token").asText(null),open=n.path("open_id").asText(null),scopes=n.path("scope").asText("");long ae=n.path("expires_in").asLong(),re=n.path("refresh_expires_in").asLong(365L*86400);if(access==null||refresh==null||open==null||ae<=0)throw new TikTokApiException("AUTH_REAUTH_REQUIRED","TikTok token response was incomplete",false);Instant now=Instant.now();return new Token(open,access,refresh,now.plusSeconds(ae),now.plusSeconds(re),scopes);}
 private JsonNode post(String path,String access,String body){return send(HttpRequest.newBuilder(URI.create(p.getApiBaseUrl()+path)).timeout(p.getReadTimeout()).header("Authorization","Bearer "+access).header("Content-Type","application/json; charset=UTF-8").POST(HttpRequest.BodyPublishers.ofString(body)).build(),false);}
 private JsonNode send(HttpRequest req,boolean token){try{HttpResponse<byte[]> r=http.send(req,HttpResponse.BodyHandlers.ofByteArray());if(r.body().length>MAX_JSON)throw new TikTokApiException("PROVIDER_INVALID_RESPONSE","TikTok response exceeded the safety limit",false);JsonNode n=json.readTree(r.body());String code=token?n.path("error").asText(""):n.path("error").path("code").asText("ok");if(r.statusCode()/100!=2||(!code.isBlank()&&!"ok".equals(code)))throw map(r.statusCode(),code,"TikTok rejected the request",false);return n;}catch(InterruptedException e){Thread.currentThread().interrupt();throw new TikTokApiException("PROVIDER_TEMPORARY","TikTok request was interrupted",true);}catch(IOException e){throw new TikTokApiException("PROVIDER_TEMPORARY","TikTok is temporarily unavailable",true);}}
 private TikTokApiException map(int status,String provider,String msg,boolean ambiguous){if(status==401)return new TikTokApiException("AUTH_REAUTH_REQUIRED","TikTok authorization expired",false);if(status==429)return new TikTokApiException("RATE_LIMITED","TikTok rate limit reached",true);if("scope_not_authorized".equals(provider))return new TikTokApiException("SCOPE_NOT_AUTHORIZED","TikTok video.publish permission is missing",false);if(status>=500)return new TikTokApiException(ambiguous?"PROVIDER_OUTCOME_UNKNOWN":"PROVIDER_TEMPORARY",msg,true,ambiguous);return new TikTokApiException("CREATOR_RESTRICTION",msg,false);}
 private void validateUploadUrl(String value){if(value==null)throw new TikTokApiException("PROVIDER_INVALID_RESPONSE","TikTok returned no upload URL",false);URI u=URI.create(value);String h=u.getHost();if(!"https".equalsIgnoreCase(u.getScheme())||h==null||!(h.equals("open-upload.tiktokapis.com")||h.endsWith(".tiktokapis.com")))throw new TikTokApiException("PROVIDER_INVALID_RESPONSE","TikTok returned an invalid upload destination",false);}
 private String form(Map<String,String> values){StringJoiner j=new StringJoiner("&");values.forEach((k,v)->j.add(enc(k)+"="+enc(v)));return j.toString();}
 private static String enc(String v){return URLEncoder.encode(v,StandardCharsets.UTF_8);} private String q(String v){try{return json.writeValueAsString(v==null?"":v);}catch(Exception e){throw new IllegalArgumentException(e);}}
}
