package com.fdmultimedia.api.publishing.tiktok;
import com.fdmultimedia.api.accounts.*; import com.fdmultimedia.api.assets.*; import com.fdmultimedia.api.publishing.*; import com.fdmultimedia.api.publishing.instagram.InstagramDriveOutcome; import java.io.*; import java.net.*; import java.net.http.*; import java.nio.file.*; import java.time.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class TikTokPublishingService {
 private final TikTokApiClient api; private final TikTokAccountConnectionService connection; private final TikTokPublicationSettingsRepository settings; private final PublicationProviderStateRepository states; private final ObjectStorageService storage; private final TikTokProperties properties; private final Clock clock; private final HttpClient sourceClient;
 public TikTokPublishingService(TikTokApiClient api,TikTokAccountConnectionService c,TikTokPublicationSettingsRepository s,PublicationProviderStateRepository ps,ObjectStorageService os,TikTokProperties p,Clock clock){this.api=api;connection=c;settings=s;states=ps;storage=os;properties=p;this.clock=clock;sourceClient=HttpClient.newBuilder().connectTimeout(p.getConnectTimeout()).followRedirects(HttpClient.Redirect.NEVER).build();}
 @Transactional public InstagramDriveOutcome drive(Publication publication){SocialAccount account=publication.getSocialAccount();TikTokPublicationSettings cfg;String token;try{cfg=settings.findByPublication(publication).orElseThrow(()->new TikTokApiException("MEDIA_NOT_ELIGIBLE","TikTok publishing settings are missing",false));token=connection.validAccessToken(account);}catch(RuntimeException e){return fail(e);}PublicationProviderState state=states.findByPublication(publication).orElse(null);Instant now=Instant.now(clock);
  if(state==null){TikTokModels.CreatorInfo creator;try{creator=api.creatorInfo(token);validate(publication.getAsset(),cfg,creator,publication.getCaption());TikTokModels.Init init=api.initialize(token,cfg,publication.getCaption(),publication.getAsset().getFileSizeBytes());state=states.saveAndFlush(new PublicationProviderState(publication,"TIKTOK",init.publishId(),"UPLOAD_PENDING",now));state.prepareUpload(init.uploadUrl(),now);}catch(RuntimeException e){return fail(e);}}
  if("PUBLISHED".equals(state.getState()))return InstagramDriveOutcome.published(state.getProviderContainerId(),state.getProviderMediaId());
  if("OUTCOME_UNKNOWN".equals(state.getState()))return InstagramDriveOutcome.failure("PROVIDER_OUTCOME_UNKNOWN","TikTok upload outcome requires manual review",true);
  if("UPLOAD_PENDING".equals(state.getState())){Path file=null;try{file=Files.createTempFile("fdm-tiktok-",".media");download(publication.getAsset(),file);api.upload(state.getProviderUploadUrl(),file,contentType(publication.getAsset()));state.markProcessing(now);}catch(InterruptedException e){Thread.currentThread().interrupt();state.markOutcomeUnknown(now);return InstagramDriveOutcome.failure("PROVIDER_OUTCOME_UNKNOWN","TikTok upload was interrupted after initialization",true);}catch(Exception e){state.markOutcomeUnknown(now);return InstagramDriveOutcome.failure("PROVIDER_OUTCOME_UNKNOWN","TikTok upload outcome requires manual review",true);}finally{if(file!=null)try{Files.deleteIfExists(file);}catch(IOException ignored){}}return InstagramDriveOutcome.inProgress();}
  try{TikTokModels.Status status=api.status(token,state.getProviderContainerId());return switch(status.status()){case "PUBLISH_COMPLETE"->{state.markPublished(status.publicPostId(),Instant.now(clock));yield InstagramDriveOutcome.published(state.getProviderContainerId(),status.publicPostId());}case "FAILED"->InstagramDriveOutcome.failure("PROVIDER_PROCESSING_FAILED",safe(status.failReason()),true);default->InstagramDriveOutcome.inProgress();};}catch(RuntimeException e){return fail(e);}}
 private void validate(MediaAsset a,TikTokPublicationSettings s,TikTokModels.CreatorInfo c,String caption){if(!Boolean.TRUE.equals(a.getHasVideo())||a.getFileSizeBytes()==null||a.getFileSizeBytes()<=0||a.getFileSizeBytes()>properties.getMaxVideoBytes())throw new TikTokApiException("MEDIA_NOT_ELIGIBLE","TikTok requires an eligible video",false);if(a.getDurationMs()==null||a.getDurationMs()<=0||a.getDurationMs()>c.maxVideoPostDurationSec()*1000L)throw new TikTokApiException("MEDIA_NOT_ELIGIBLE","Video exceeds the creator's current duration limit",false);if(!c.privacyLevelOptions().contains(s.getPrivacyLevel()))throw new TikTokApiException("PRIVACY_OPTION_INVALID","Selected TikTok privacy option is no longer available",false);if((!s.isDisableComment()&&c.commentDisabled())||(!s.isDisableDuet()&&c.duetDisabled())||(!s.isDisableStitch()&&c.stitchDisabled()))throw new TikTokApiException("CREATOR_RESTRICTION","Selected interaction setting is unavailable",false);if(caption!=null&&caption.codePointCount(0,caption.length())>2200)throw new TikTokApiException("MEDIA_NOT_ELIGIBLE","TikTok caption exceeds 2200 Unicode characters",false);}
 private void download(MediaAsset asset,Path target)throws IOException,InterruptedException{StorageAccess access=storage.presignedGet(asset.getStorageKey());HttpResponse<InputStream> r=sourceClient.send(HttpRequest.newBuilder(URI.create(access.url())).timeout(properties.getUploadTimeout()).GET().build(),HttpResponse.BodyHandlers.ofInputStream());if(r.statusCode()/100!=2){r.body().close();throw new IOException("source unavailable");}long max=properties.getMaxVideoBytes(),total=0;try(InputStream in=r.body();OutputStream out=Files.newOutputStream(target)){byte[] b=new byte[64*1024];for(int n;(n=in.read(b))>=0;){total+=n;if(total>max)throw new IOException("source too large");out.write(b,0,n);}}if(total!=asset.getFileSizeBytes())throw new IOException("source size mismatch");}
 private InstagramDriveOutcome fail(RuntimeException e){if(e instanceof TikTokApiException t)return InstagramDriveOutcome.failure(t.code(),safe(t.getMessage()),!t.retryable());return InstagramDriveOutcome.failure("PROVIDER_TEMPORARY","TikTok publishing is temporarily unavailable",false);} private String safe(String s){return s==null||s.isBlank()?"TikTok processing failed":s.substring(0,Math.min(500,s.length()));} private String contentType(MediaAsset a){return switch(a.getContentType()==null?"":a.getContentType()){case "video/quicktime"->"video/quicktime";case "video/webm"->"video/webm";default->"video/mp4";};}
}
