package com.fdmultimedia.api.publishing.tiktok;
import com.fdmultimedia.api.accounts.*; import com.fdmultimedia.api.auth.AuthService; import com.fdmultimedia.api.auth.security.AuthenticatedUser; import com.fdmultimedia.api.workspaces.*; import java.time.*; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Service public class TikTokAccountConnectionService {
 private static final String PLATFORM="TIKTOK", REQUIRED="video.publish";
 private final AuthService auth; private final SocialAccountRepository accounts; private final SocialCredentialService credentials; private final SocialOAuthStateService states; private final TikTokApiClient api; private final TikTokProperties properties; private final Clock clock;
 public TikTokAccountConnectionService(AuthService a,SocialAccountRepository r,SocialCredentialService c,SocialOAuthStateService s,TikTokApiClient api,TikTokProperties p,Clock k){auth=a;accounts=r;credentials=c;states=s;this.api=api;properties=p;clock=k;}
 @Transactional public String start(AuthenticatedUser principal){configured();WorkspaceMembership m=auth.currentMembershipFor(principal);return api.authorizationUrl(states.create(m.getWorkspace(),m.getUser(),PLATFORM,properties.getOauthStateTtl()));}
 @Transactional public TikTokCallbackResult callback(String state,String code,String error){if(error!=null&&!error.isBlank())return TikTokCallbackResult.fail("denied");SocialOAuthState oauth;try{oauth=states.consume(state,PLATFORM);}catch(InvalidOAuthStateException e){return TikTokCallbackResult.fail("invalid_state");}if(code==null||code.isBlank())return TikTokCallbackResult.fail("missing_code");try{TikTokModels.Token t=api.exchange(code);if(!hasScope(t.scopes(),REQUIRED))return TikTokCallbackResult.fail("missing_scope");TikTokModels.CreatorInfo info=api.creatorInfo(t.accessToken());String name=info.nickname().isBlank()?(!info.username().isBlank()?info.username():t.openId()):info.nickname();Instant now=Instant.now(clock);SocialAccount account=accounts.findByWorkspaceAndPlatformAndExternalAccountId(oauth.getWorkspace(),SocialPlatform.TIKTOK,t.openId()).map(x->{x.reactivate(name,now);return x;}).orElseGet(()->accounts.save(new SocialAccount(oauth.getWorkspace(),SocialPlatform.TIKTOK,name,t.openId(),oauth.getUser(),now)));credentials.storeOAuthTokens(account,"TIKTOK_OAUTH2",t.accessToken(),t.refreshToken(),t.accessExpiresAt(),t.refreshExpiresAt(),t.scopes());return TikTokCallbackResult.ok();}catch(TikTokApiException e){return TikTokCallbackResult.fail("exchange_failed");}}
 @Transactional public TikTokModels.CreatorInfo capabilities(AuthenticatedUser principal,java.util.UUID id){Workspace w=auth.currentMembershipFor(principal).getWorkspace();SocialAccount a=accounts.findByWorkspaceAndId(w,id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Social account not found"));if(a.getPlatform()!=SocialPlatform.TIKTOK||a.getStatus()!=SocialAccountStatus.ACTIVE)throw new ResponseStatusException(HttpStatus.CONFLICT,"TikTok account is not active");return api.creatorInfo(validAccessToken(a));}
 @Transactional public SocialAccountSummary disconnect(AuthenticatedUser principal,java.util.UUID id){Workspace w=auth.currentMembershipFor(principal).getWorkspace();SocialAccount a=accounts.findByWorkspaceAndId(w,id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Social account not found"));if(a.getPlatform()!=SocialPlatform.TIKTOK)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Account is not TikTok");credentials.remove(a);a.markDisconnected(Instant.now(clock));return new SocialAccountSummary(a.getId(),a.getPlatform(),a.getDisplayName(),a.getExternalAccountId(),a.getStatus(),a.getCreatedAt(),a.getUpdatedAt());}
 @Transactional public String validAccessToken(SocialAccount a){SocialCredentialService.OAuthCredential c=credentials.decryptOAuthCredential(a);if(c.accessExpiresAt()!=null&&c.accessExpiresAt().isAfter(Instant.now(clock).plus(properties.getRefreshMargin())))return c.accessToken();try{TikTokModels.Token t=api.refresh(c.refreshToken());if(!hasScope(t.scopes(),REQUIRED))throw new TikTokApiException("SCOPE_NOT_AUTHORIZED","TikTok video.publish permission is missing",false);credentials.storeOAuthTokens(a,"TIKTOK_OAUTH2",t.accessToken(),t.refreshToken(),t.accessExpiresAt(),t.refreshExpiresAt(),t.scopes());return t.accessToken();}catch(TikTokApiException e){a.markError(Instant.now(clock));throw e;}}
 private boolean hasScope(String s,String wanted){return s!=null&&java.util.Arrays.stream(s.split(",")).map(String::trim).anyMatch(wanted::equals);} private void configured(){if(!properties.isConfigured())throw new ResponseStatusException(HttpStatus.CONFLICT,"TikTok integration is not configured");}
}
