package com.fdmultimedia.api.jobs;

public enum JobType {
    SYSTEM_TEST,
    IMPORT_MEDIA,
    INSPECT_MEDIA,
    CREATE_CLIP,
    CREATE_SOCIAL_VERTICAL,
    ANALYZE_HIGHLIGHTS,
    TRANSCRIBE_MEDIA,
    PUBLISH_MEDIA,
    GENERATE_SOCIAL_COPY
}
