CREATE TABLE decision_applications (
    id UUID PRIMARY KEY,
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    experiment_id UUID NOT NULL REFERENCES experiments(id) ON DELETE RESTRICT,
    experiment_name_snapshot TEXT NOT NULL,
    experiment_decision_id UUID NOT NULL REFERENCES experiment_decisions(id) ON DELETE RESTRICT,
    robot_id UUID NOT NULL REFERENCES robots(id) ON DELETE RESTRICT,
    robot_name_snapshot TEXT NOT NULL,
    application_version TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('APPLIED','ROLLED_BACK')),
    selected_variant_key TEXT NOT NULL CHECK (selected_variant_key IN ('A','B')),
    target_persona_id UUID REFERENCES personas(id) ON DELETE RESTRICT,
    target_persona_name_snapshot TEXT NOT NULL,
    previous_persona_id UUID REFERENCES personas(id) ON DELETE RESTRICT,
    previous_persona_name_snapshot TEXT,
    preview_fingerprint CHAR(64) NOT NULL,
    decision_evidence_fingerprint CHAR(64) NOT NULL,
    requested_by_user_id UUID NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    requested_at TIMESTAMPTZ NOT NULL,
    applied_by_user_id UUID NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    applied_at TIMESTAMPTZ NOT NULL,
    robot_updated_at_before TIMESTAMPTZ NOT NULL,
    robot_updated_at_after TIMESTAMPTZ NOT NULL,
    no_op BOOLEAN NOT NULL,
    confirmed_older_decision BOOLEAN NOT NULL,
    confirmed_not_ready_decision BOOLEAN NOT NULL,
    confirmed_active_experiment BOOLEAN NOT NULL,
    rollback_of_application_id UUID REFERENCES decision_applications(id) ON DELETE RESTRICT,
    idempotency_key VARCHAR(100) NOT NULL CHECK (char_length(idempotency_key) BETWEEN 1 AND 100),
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (workspace_id, experiment_decision_id, robot_id, idempotency_key)
);
CREATE INDEX decision_applications_history_idx ON decision_applications (experiment_id, applied_at DESC, id DESC);
CREATE INDEX decision_applications_robot_idx ON decision_applications (robot_id, applied_at DESC);
